// <auto-generated />
using System;
using C_ManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace C_ManagementSystem.Migrations
{
    [DbContext(typeof(CustomerContext))]
    partial class CustomerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("C_ManagementSystem.Models.ContactModel", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("ContactModels");
                });

            modelBuilder.Entity("C_ManagementSystem.Models.FrameLensModel", b =>
                {
                    b.Property<string>("WoID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LensAddOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LensCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LensMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LensType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Total")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WoID");

                    b.ToTable("FrameLensModels");
                });

            modelBuilder.Entity("C_ManagementSystem.Models.JobModel", b =>
                {
                    b.Property<string>("JobID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<string>("FrameDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JobDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NYSTax")
                        .HasColumnType("bit");

                    b.Property<float>("Subtotal")
                        .HasColumnType("real");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("JobID");

                    b.ToTable("JobModels");
                });

            modelBuilder.Entity("C_ManagementSystem.Models.RxModel", b =>
                {
                    b.Property<string>("RxID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddPower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ODAxis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ODCyl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ODSph")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSAxis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSCyl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSSph")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientPD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RxID");

                    b.ToTable("RxModels");
                });
#pragma warning restore 612, 618
        }
    }
}
